apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-basic
  namespace: confluent
spec:
  image: ${FLINK_IMAGE}
  flinkVersion: ${FLINK_VERSION}
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "1024m"
      cpu: 0.5